---
title: "Modeling: Predicting Diabetes Risk"
author: "Keshav Ramesh"
format: html
---

## Introduction


```{r}
library(tidyverse)
library(tidymodels)
library(caret)
library(yardstick)
library(glmnet)
library(rpart.plot)
```

```{r}
data_raw = read_csv("diabetes_binary_health_indicators_BRFSS2015.csv")

# convert variables to factors
diabetes_data = data_raw %>%
  mutate(
    Diabetes_binary = factor(Diabetes_binary, levels = c(0, 1), labels = c("No Diabetes", "Diabetes")),
    PhysActivity = factor(PhysActivity, levels = c(0, 1), labels = c("No", "Yes")),
    AgeGroup = factor(Age, levels = 1:13, labels = c(
  "18–24",
  "25–29",
  "30–34",
  "35–39",
  "40–44",
  "45–49",
  "50–54",
  "55–59",
  "60–64",
  "65–69",
  "70–74",
  "75–79",
  "80+"
))
)

```

```{r}
set.seed(101)

diabetes_split = initial_split(diabetes_data, prop = .7)
diabetes_train = training(diabetes_split)
diabetes_test = testing(diabetes_split)

cv_folds <- vfold_cv(diabetes_train, 5)

diabetes_recipe = recipe(Diabetes_binary ~ BMI + Age + PhysActivity, data = diabetes_train) %>%
  step_normalize(all_numeric(), -Diabetes_binary)
```

Log Regression Model

```{r}

log_spec <- logistic_reg() %>%
  set_engine("glm")

log_workflow <- workflow() %>%
  add_model(log_spec) %>%
  add_recipe(diabetes_recipe)


log_res <- log_workflow %>%
  fit_resamples(
    resamples = cv_folds,
    metrics = metric_set(mn_log_loss),
    control = control_resamples(save_pred = TRUE)
  )

collect_metrics(log_res)
```

Fit Log Model
```{r}
log_res_fit = log_workflow %>%
  fit(diabetes_train)

conf_mat(diabetes_train %>%
           mutate(estimate = log_res_fit %>% 
                    predict(diabetes_train) %>%
                    pull()), Diabetes_binary, estimate)

conf_mat(diabetes_test %>%
           mutate(estimate = log_res_fit %>% 
                    predict(diabetes_test) %>%
                    pull()), Diabetes_binary, estimate)

final_log_model = log_workflow %>%
  fit(diabetes_data)

tidy(final_log_model)

```




Classification Tree
```{r}
tree_spec <- decision_tree(
  cost_complexity = tune(),
  tree_depth = tune(),
  min_n = 20
) %>%
  set_engine("rpart") %>%
  set_mode("classification")


tree_workflow <- workflow() %>%
  add_recipe(diabetes_recipe) %>%
  add_model(tree_spec)



tree_grid <- grid_regular(
  cost_complexity(),
  tree_depth(),
  levels = c(cost_complexity = 10, tree_depth = 5)
)



tree_fits <- tree_workflow |> 
  tune_grid(resamples = bike_CV_folds,
            grid = tree_grid)

tree_fits |>
  collect_metrics() |>
  filter(.metric == "mn_log_loss") |>
  arrange(mean)


tree_best_params <- select_best(tree_fits, metric = "mn_log_loss")

tree_final_workflow <- tree_workflow |>
  finalize_workflow(tree_best_params)

tree_final_fit <- tree_final_workflow |>
  last_fit(diabetes_split)

tree_final_fit |>
  collect_metrics()

tree_final_model <- extract_workflow(tree_final_fit) 
tree_final_model

tree_final_model %>%
  extract_fit_engine() %>%
  rpart.plot::rpart.plot(roundint = FALSE)

```

## Random Forest 










